# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    # 每小时的第0/12/24/36/48分钟各执行一次
    - cron: '11,25,35,46,58 * * * *'
  push:
    branches:
      - 'main'
    paths:
      - '**.yml'
permissions:
  contents: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov requests BeautifulSoup4
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run main.py
      run: python main.py > output.log 2>&1
    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: python-output
        path: output.log
    - name: Commit log file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git reset -- ./.github/workflow/Python-app.yaml
        git commit -m "Update all files except a.yaml [skip ci]" || echo "No changes to commit"
        git push
